### ISSUE TITLE
Broken link to this repo on npm.com

### ISSUE THREAD

**Issue by dmt0** [ogbotemi-2000/rmrf-css#2]
<img width="528" alt="image" src="https://github.com/ogbotemi-2000/rmrf-css/assets/2717746/5bcc6797-e208-492a-b45c-4f6adbdb3b62">

**Comment by ogbotemi-2000** [comment]
It has now been fixed, thanks a million 😊

**Comment by ogbotemi-2000** [comment]
PS: Do share your thoughts for further engagement via the discussion thread: https://github.com/ogbotemi-2000/rmrf-css/discussions
